### ISSUE TITLE
multislider.setSliderValue() is broken

### ISSUE THREAD

**Issue by futuremarc** [lsu-emdm/nexusUI#13]
I can't seem to call the method .setSliderValue on any multisliders, it returns "Uncaught ReferenceError: msg is not defined nexusUI.js: 3368"

**Comment by taylorbf** [comment]
Thanks for pointing out this bug. I have just pushed fix for this error in the latest build. For example the code `multislider1.setSliderValue(0,0.5)` will set multislider1's first slider to the value 0.5. Let me know if you still experience any problems.
