### ISSUE TITLE
Colors widget load time

### ISSUE THREAD

**Issue by geraldo** [lsu-emdm/nexusUI#14]
Using several (and big) colors widgets I noticed that nexus loading time slowed down quite a lot. To make it load fast again I substitued the two for-loops in *colors.prototype.draw* function by a bitmap image:

```javascript
var img = new Image();
img.src = 'img/colors.png';
$(img).load(function(){
	context.drawImage(img,0,0);
});
```

**Comment by taylorbf** [comment]
Yes, you are right that the colors widget takes too long to generate its UI and slows everything down. We have tried to avoid bundling an image in with the library, but we will investigate possible ways to generate a faster color picker. I will keep this issue open until a better solution is implemented.

**Comment by taylorbf** [comment]
I overhauled the colors widget to use linear gradients (via the canvas api) to achieve the same functionality as the old colors widget. It loads much faster now and no longer loses saturation when it is resized. The latest version (1.0.5) has this implemented.

Thanks again for bringing this to my attention!

**Comment by geraldo** [comment]
Thanks for your quick fix, everythings works fine now with the linear gradients. Keep up your good work!
