### ISSUE TITLE
Integer number

### ISSUE THREAD

**Issue by AlesTsurko** [lsu-emdm/nexusUI#16]
Does it possible to get (and display) int value from the number element? I try to .set rounded value, but it was very "glitch" solution... Don't found anything about this in API documentation.

**Comment by taylorbf** [comment]
Hi Ales, I have merged an updated number widget which has a .decimalPlaces property, letting you specify how many digits you want after the decimal. Good idea, thanks.

`number1.decimalPlaces = 0` will make the interface output integers.

**Comment by AlesTsurko** [comment]
Great! Thanks!
