### ISSUE TITLE
Envelope - add more segments/joints

### ISSUE THREAD

**Issue by jesseallison** [lsu-emdm/nexusUI#22]
We should be able to add more joints/segments to the envelope. This would allow for an AD(S)R as well as more complex envelopes.

**Comment by therewasaguy** [comment]
I prototyped this here:

https://github.com/therewasaguy/nexusUI/blob/envmulti/lib/widgets/envmulti.js

I have it as a separate widget "envmulti," but should it be part of the regular envelope, and just add an option to set the number of joints?

**Comment by taylorbf** [comment]
Looks great Jason, I will try this out ASAP. Feel free to PR any of your additions to the dev branch if you ever want to!

More likely, we should use a multi-point envelope function like yours as the normal "envelope" widget and make the current version a stripped-down "env" or "ramp" option for mobile users.

**Comment by therewasaguy** [comment]
Thanks @taylorbf, I'd like to clean this up for NexusUI and send a PR, hopefully later this week.

This version is tweaked for my particular use case, for example it [uses an audio context for timing](https://github.com/therewasaguy/nexusUI/blob/envmulti/lib/widgets/envmulti.js#L207), so I won't include that stuff in the PR.

**Comment by taylorbf** [comment]
Oh wonderful, moving the matrix sequencer and envelope to the WAAClock or Tone.Transport interval system is something I've been meaning to do (and have started to do in the sequencers over [here](http://taylorbf.github.io/ToneJam/)). I'll turn this into its own issue.

**Comment by taylorbf** [comment]
Added in v1.0.8, thanks to @therewasaguy
