### ISSUE TITLE
Animation is hidden in the documentation

### ISSUE THREAD

**Issue by jesseallison** [lsu-emdm/nexusUI#25]
The documentation is gone that listed how to enable and use animation on any of the objects.

**Comment by taylorbf** [comment]
Animation is now back in the documentation at [nexusosc.com](http://nexusosc.com), towards the bottom of the page. 

The animation now is not great... I'm considering phasing it out eventually out in favor of the new *ghost* or *remix* widget which captures gestures and replays them.
