### ISSUE TITLE
It's posible to reload nexusui?

### ISSUE THREAD

**Issue by hugoruscitti** [lsu-emdm/nexusUI#27]
hi!, i'm working in a emberjs application with nexusui widgets, but i don't found
how to encapsulate nexusui widgets correctly.

Normally, any javascript library i use has some method to create widgets programatically. I need
to create the widget's canvas with some like "createElement" and then attack nexusui to that
element, this is possible with nexusui?

I see that nexus ui uses the document's onload event to init the library on all canvas elements, it's the only way to init widgets?

Thanks!

**Comment by taylorbf** [comment]
Hi Hugo, yes nexusUI includes methods for creating new widgets programatically.

I think you want to use `nx.add()` or `nx.transform()`

The API documentation for each is [here](http://nexusosc.com/api/#nexusui-api-nx-nxadd-type-settings).

Here are some code examples. This will add 3 nexusUI dials with different parameters. It generates a new <canvas> for each widget.

```js
nx.add('dial')
nx.add('dial',{w: 40, h: 40})
nx.add('dial',{w: 40, h: 40, x: 100, y: 100, name: 'volume', parent: 'parentID'})
```

or you can transform an existing <canvas> into a nexusUI widget.

```js
nx.transform('canvasID', 'dial')
```

**Comment by hugoruscitti** [comment]
Awesome!! thanks!!!
