### ISSUE TITLE
every click related widget is broken in firefox

### ISSUE THREAD

**Issue by bitterulf** [lsu-emdm/nexusUI#33]
I was revisiting the nexusUI to build something with it but it isn't working anymore in firefox (38.0.5) but is still working in IE.

It seems that clicks are not processed.

**Comment by taylorbf** [comment]
What kind of device are you using? Specifically, is it a touchscreen computer monitor? I have not yet been able to recreate this issue.

**Comment by bitterulf** [comment]
I am using a standard desktop system with windows and mouse.
But i was also unable to reproduce the bug on fresh firefox installations.
My Firefox was exact the same version and the portable versions i downloaded to test.

My guess is that some bigger steps in the firefox update process went wrong.
I did a factory reset and that fixed the problem.

But i still wonder why it just affected nexusui and nothing else.
