### ISSUE TITLE
widget.getName() returns empty string

### ISSUE THREAD

**Issue by amitayd** [lsu-emdm/nexusUI#38]
It seems like widget.getName() does a regexp match to find the widget type (i.e. "dial", "button", etc) according to the constructor function name.

See:
https://github.com/lsu-emdm/nexusUI/blob/master/lib/core/widget.js#L347

This might be somewhat brittle and error prone, and it seems that indeed the widgets that I checked use an anonymous constructor function:

    var dial = module.exports = function(target) {

So the regex finds no match and returns an empty string.

Perhaps the widget type should be registered by the widget itself in a more explicit way?

**Comment by taylorbf** [comment]
Hey @amitayd, you are correct that `.getName()` is a legacy method at this point and is no longer working. I have just added a property `widget.type` which accomplishes the same objective.

For a dial widget called `dial1`

```
dial1.type  // returns "dial"
```

This is in the dev branch for now. I am planning a merge to master this month but I need to clean up the branch first.
