### ISSUE TITLE
websockets?

### ISSUE THREAD

**Issue by brucelane** [lsu-emdm/nexusUI#45]
hi,
what if we could have websockets instead/in complement of OSC?

**Comment by taylorbf** [comment]
Hi Bruce,

Great question. NexusUI can and should be used with websockets. There are a few ways to go about this. I will make it a priority to document this ability better.

#### sendsTo("node") 

If you are using socket.io and have a websocket defined as `socket` on the client side, you can send directly through the socket by using this setting:

```js
nx.onload = function() {
    nx.sendsTo("node")`
}
```

This passes all interface data through a `socket.emit('nx', data)` so you can receive it on your server by making a listener for 'nx' events.

There is demo code for this [here](https://github.com/lsu-emdm/nx-NodeDemo), but it is a little old. 

#### custom transmit function

You can also define a custom transmit function for the interface, in which you could forward data.

```js
nx.sendsTo(function(data) {
   // some code that sends to the data to your websocket
})
```

#### forward events using .on()

The easiest method would be to use the regular javascript `.on()` listeners to forward data. However this method would be less efficient.

```
slider1.on('*',function(data) {
   // add some code that forwards your data to a server
})
```

We used this last method in some demo servers [here](https://github.com/lsu-emdm/WAC.io/tree/master/servers) using the [rhizome](https://github.com/sebpiq/rhizome) websocket server toolkit.

Hope this helps!

**Comment by brucelane** [comment]
I was thinking of using websockets without having node.js, which is more portable, a ws server and a nexusUI ws client, like https://github.com/labatrockwell/ofxLibwebsockets does

**Comment by brucelane** [comment]
example: use nexusUI on my Windows Phone to control Cinder/openFrameworks apps on the desktop for VJing

**Comment by taylorbf** [comment]
Ah, I see. I may be a little confused about what you're after. I will leave this request open in case anyone else wants to chime in.

It seems to me that the client-side data from our UI can be forwarded using any ws toolkit you want to use. We have templates in Rails, Socket.IO, Rhizome, and PHP, which support a wide variety of use cases, and have been used to send data to VJ software. If we do package NexusUI with a server in the future, we will most likely use node.

**Comment by brucelane** [comment]
just that I write my own VJ software which has a websockets server inside.
you can close this... I got all the info I need now, it's great there is all that options already!
thank you
Bruce

**Comment by taylorbf** [comment]
OK, I will keep this in mind as we develop and as we look at server options. Thanks for the input --

Ben
