### ISSUE TITLE
showLabels only works for sliders

### ISSUE THREAD

**Issue by marcokuhn** [lsu-emdm/nexusUI#46]
Hi,

i like to display lables on a toggle element but it doesn`t work.
It seems that label work only for sliders.
That`s the way how I tried it.

nx.showLabels = true;
nx.setLabels("on");

<canvas nx="toggle" id="mute" label="mute" height="30" width="100" ></canvas>
     
Best,
Marco

**Comment by taylorbf** [comment]
Hi Marco, thanks for the comment. I just updated the master branch so that the global nx.setLabels("on") method works.

These labels can be useful, however their style is a bit underwhelming right now. Updating the label mechanism is on my to-do list.

**Comment by marcokuhn** [comment]
thanks a lot, but the canvas attribute label="..." only works actually for
slider.
nexusUI use the id as a label.

2015-07-20 18:34 GMT+02:00 Ben Taylor <notifications@github.com>:
