### ISSUE TITLE
Better labels

### ISSUE THREAD

**Issue by taylorbf** [lsu-emdm/nexusUI#48]
This is a must have, at the current point of development. I see three possible mechanisms:

**On canvas**
One way is to draw the text at the bottom of each element's canvas, like it is now, but to shrink each GUI so there is no overlap. However, this means that the user needs to account for that text when they size their widget. A 50x50 button would need to have a canvas sized 50x70 to account for the extra text space. I don't like the idea of making the user do that math.

`<canvas nx="button" label="ping" width="50px" height="70px"></canvas>`

I suppose we could resize the canvas automatically, to turn a 50x50 canvas into a 50x70 canvas, with a warning that adding a label increases a canvas by 20px.

Regardless, I don't think text on <canvas> looks great, it doesn't have automatic wordwrap, etc.

**Modules**
I have been thinking more and more about creating NexusUI modules –– a <div> with several widgets and text labels inside. In this case, the text labels could be made with regular HTML. These modules could be created with web components (temperamental) or just with a <div>, like this:

```
<div nx="button" label="start" style="width:50px;height:50px;"></div>
```
This div could be filled automatically with a button and a <div> text label.

A nice aspect of this method is that it could quickly lead to larger modules, like `<div nx="sequencer">` which could include a matrix, toggle, bpm dial, and labels for each.

**Leave it to the user**
Since widget's are plain HTML canvases right now, a user can fairly easily add a div label that fits the style of their site, using the following paradigm:

```
<div>
   <canvas nx="button"></canvas>
   <div class="label">Start</div>
</div>
```

**Comment by taylorbf** [comment]
I sketched up an implementation of the first option, in a new branch. You can view it [here](http://www.nexusosc.com/labels/).

Code example:

```
<canvas nx="dial" label="Frequency" min="50" max="1000"></canvas>
```

This means that if you want a 50px x 50px dial, you should actually give the canvas height:80px in order to have space for a 30px label. You can also change the label size using `nx.labelSize()`

I would love feedback on any of this It's clear that labels are a necessary feature. There are many options (should labels be declarative in HTML or be added via JS?) which are up for debate when creating this.

**Comment by dsholmes** [comment]
I think your example would be great and really convenient. In documentation just let people know the label will be a certain size, position, and font, and that any customization can be done using the other methods you described instead.

**Comment by taylorbf** [comment]
Good point, there should also be something like:

```
nx.labelAlign("left")
nx.labelFont("courier")
```

Default font for the whole library right now is [Open Sans](https://www.google.com/fonts/specimen/Open+Sans)

If a project needs more customization than that, I think it is up to the user to just write the HTML/CSS

**Comment by taylorbf** [comment]
Oh, maybe you were suggesting that we NOT allow for much customization of the label. I.e. if someone wants more compelx labels, they should just write the HTML/CSS. Adding nx.labelAlign() and nx.labelFont() wouldn't take much....  But yes it is clear that it should be limited, because there are just too many ways to customize a label.

**Comment by dsholmes** [comment]
I think those designations are fine but should have a global entry point. So you could set the alignment and font of every label, then maybe you can call that on each object if necessary. If you do font like that, would you also do color?

**Comment by taylorbf** [comment]
Color for the label is currently `nx.colors.black`. I've tried to use a limited color palette for all of nexusUI, for easy skinning. If you have a dark theme, you will usually do something like `nx.colors.black="#FFFFFF"` anyway.

So, yes we could make a separate font color, but using `nx.colors.black` doesn't seem to raise any problems (that I've noticed), and is a bit more streamlined.

**Comment by dsholmes** [comment]
Cool. I think it’s best to limit all of these customization options so that it’s easier to use (and look good) for less technical audiences. More web savvy designers will always be able to customize using the other methods.

**Comment by taylorbf** [comment]
This proposal has been merged. More work on customization of labels will have to be done at a later date when I have more time.
