### ISSUE TITLE
Resizing widgets after creation

### ISSUE THREAD

**Issue by dyfer** [lsu-emdm/nexusUI#51]
Hello,

Thanks for the NexusUI, it looks great.
I'm trying to incorporate it in my project and I have trouble resizing/moving the widget after it's created. Is that not possible currently?

Thanks!

**Comment by taylorbf** [comment]
Hi there @dyler! I must have missed this when you posted it, and I'm so sorry for that!

Yes you can resize widgets after creating them. Given a widget `slider1`:

```
slider1.resize(300,100)
```

That will make the slider 300px wide and 100 tall.

To move a widget, that depends on what kind of CSS you have on the widget. If your widget has CSS of `position:absolute`, you could do:

```
slider1.canvas.style.top = "100px"
slider1.canvas.style.left = "200px"
```

Hope this helps!

**Comment by dyfer** [comment]
Thanks! I'll go back and try it!

**Comment by Wallman** [comment]
This should be in the documentation :)
