### ISSUE TITLE
using nexusUI with npm

### ISSUE THREAD

**Issue by Tyler-Anderson** [lsu-emdm/nexusUI#52]
you have to install the extend module or nexusUI won't work.

**Comment by taylorbf** [comment]
Hi Tyler, extend should be listed as a dependency, but you are right, it's not. I'm in the midst of an update and will add this ASAP, thanks for reporting the bug.

**Comment by marsman12019** [comment]
An addon to this, it looks like you're using `window` a lot, which is causing failures on the server (where there is no window), at least in my preliminary attempts.

**Comment by taylorbf** [comment]
Hey there @marsman12019, I would love to hear more about your ideas for using nexusUI server-side. Are you thinking of loading interfaces programmatically, using `nx.add()`, from the server? 

I guess I am not sure how a front-end toolkit like this should act on a server. When I have used nexusUI with npm, I require it within browserify projects.

**Comment by marsman12019** [comment]
My uses are more utilitarian: just being able to use nexus on a website built on Node, for example, something that can use Sockets.io.

**Comment by taylorbf** [comment]
Oh, great. Yes NexusUI can and should be used with socket.io -- we do that a lot!

Check out [the response to issue #45](https://github.com/lsu-emdm/nexusUI/issues/45).

I recommend just including nexusUI as a script in the HTML page, as in the page [here](https://github.com/lsu-emdm/nx-NodeDemo/blob/master/index.html), though this demo is a bit old now.

**Comment by taylorbf** [comment]
In the latest update, the extend module is listed as a dependency.

**Comment by turbo5** [comment]
Installing from npm, I still get the 1.0.8, with the old controls design and the labels also don't appear. Do you guys have some clue why this can happen?
Thxxx
