### ISSUE TITLE
Matrix widget size updates properly upon .init() not .draw()

### ISSUE THREAD

**Issue by triss** [lsu-emdm/nexusUI#6]
If I set the following matrix's size it's not updated properly until `.init()` is called.

The documentation here indicates that it should update upon calling `.draw()`: http://www.nexusosc.com/api/#matrix

This example updates size with `.init()`: https://github.com/lsu-emdm/nexusUI/blob/388f2e55ba6b5e1043f953f7a3eddd435e44c788/examples/matrix/index.html

The following code produces the attached UI:
```
<html>
<head>   
    <script src="lib/jquery-1.11.1.min.js"></script>
    <script src="lib/nexusUI.js"></script> 

    <script>
        nx.onload = function() {
            nx.sendsTo("js");

            patternMatrix.row = 8;
            patternMatrix.col = 16;
            patternMatrix.draw();
        }
    </script>   
</head>

<body>
    <canvas nx="matrix" id="patternMatrix" width="750px" height="500px"></canvas>
</body>
</html>
```

![screenshot from 2014-11-12 12 32 42](https://cloud.githubusercontent.com/assets/474973/5010233/54ec40b6-6a68-11e4-9a8b-059276daa2c4.png)

This occurs in Google Chrome 37.0.2062.120

**Comment by taylorbf** [comment]
Hi Tristan, sorry for neglecting to update this issue after the new release.

The new API reflects that yes, a `.init()` must be called after updating the number of rows or columns. That was an error in the previous docs.
