### ISSUE TITLE
Toggle multiple keyboard eys

### ISSUE THREAD

**Issue by adowty** [lsu-emdm/nexusUI#61]
Hey Ben and Team,
This is a really great project. I'm digging into it.
I'm trying to toggle multiple keys in sustain mode.
						var onS = [0,2,4,5,7,9,11];
						for (x=0; x<onS.length; x++) { 
						keyboard1.toggle( keyboard1.keys[onS[x]], true );
						}
						var offS = [1,3,6,8,10];
						for (y=0; y<offS.length; y++) {
						keyboard1.toggle( keyboard1.keys[offS[y]], false );
						}
I think this should toggle all the white keys (in C maj). I'm getting unexpected toggling.

**Comment by taylorbf** [comment]
Thanks, yes your code is what is desired. Posted a fix to master branch. 

Details:
There was a conflict with the single-argument option for .toggle, which toggles a note on and off without having to specify true or false. In your case, when toggling a note off using `false`, it passed the condition for having only one argument. Fixed with a `===false`

**Comment by adowty** [comment]
awesome.thanks!

**Comment by adowty351** [comment]
Hi Guys,

I know I said thanks for looking into this, and it got closed, but it actually doesn't work.
I've been in other areas of a much larger project and am just getting back to this now. sorry 'bout that.
I've mega double checked my loops and arrays and they are still turning keys on and off in unexpected ways. I am using the keyboard object, not as an input for a synth, but for the user to define admissible scale tones for an audio synth that works somewhat like an autotune. this code takes output from a select which has choices like "major" and "minor" and should change the scale pattern on the keyboard object. 

```
				select22.on('*', function(data) {
					var scaleNum = (select22.sel.selectedIndex);
var modePatterns = [
						['true','false','true','false','true','true','false','true','false','true','false','true'],
						['true','false','true','true','false','true','false','true','false','true','true','false'],
						['true','true','false','false','true','true','false','true','true','false','false','true'],
						['true','false','true','false','true','false','true','true','false','true','false','true'],
						['true','false','true','false','true','false','true','false','true','false','true','false'],
						['true','false','true','false','true','false','true','true','false','true','false','true'],
						['false','true','false','true','false','true','true','false','true','false','true','true']
						]
						var noteOnOff;
						for (var i = 0; i < 12; i++) {
    					noteOnOff = modePatterns[scaleNum][i];
						keyboard1.toggle( keyboard1.keys[i], noteOnOff );
						}
						
					})
```

**Comment by adowty** [comment]
update:
I've discovered that when I run the for loop on keyboard1, it transmits the midi number / boolean pair in order from 48 to 59. however, when i toggle the keys one at a time, the midi numbers go up by 4 for some reason. There has to be a bug here.
