### ISSUE TITLE
Not able to change the font size of slider's label

### ISSUE THREAD

**Issue by cesar3dartist** [lsu-emdm/nexusUI#70]
Hi, 

I've been trying to change the size of the slider, but everytime I do it, the size of the text value inside the bar scales with it. I don't seem to be able to change the size of the text independently of the slider canvas itself. This is important to me, since I want all text on all widgets of my interface to have the same text size regardless of the size of the widget.

Any idea how to do this? I've tried already by setting styles on the <head> and also inside the <canvas> but I get the same behavior of stretched out text.

**Comment by taylorbf** [comment]
I don't have an answer for this yet... The label's don't allow for a lot of fine tuning. For customizable text, you might want to use regular HTML labals using `div` or `span`.   But I will look through the label code and see if there is a way to do it already, or a clean way to implement.

Ben
