### ISSUE TITLE
Changing dial bar click/drag behaviour

### ISSUE THREAD

**Issue by cesar3dartist** [lsu-emdm/nexusUI#71]
Currently, the dial progress bar goes around based on mouse position on the whole screen. Is there a way to set it so that it goes around depending on the click position inside the bar, and not the whole screen? 

I'm building a widget that has an html page the size of only the widget. So I need to be able to move the progress bar of the dial based on the click and drag inside the circle.

**Comment by taylorbf** [comment]
Yes, you can change the dial's `responsivity` property. The default is .004 (this means that a 1 pixel mouse motion will increase the dial .004 on a normalized scale 0-1). You can change it experimentally, perhaps try:

```
dial1.responsivity = 0.2
```

**Comment by hepiyellow** [comment]
How about controlling the dial according to polar coordinates from the dial's center?

**Comment by taylorbf** [comment]
@hepiyellow radial interaction is implemented in the forthcoming major update. Working to get it to you guys as soon as I can. 

For now I'll close this issue as the original responsivity question was solved.
