### ISSUE TITLE
output select object index rather than choice string

### ISSUE THREAD

**Issue by adowty** [lsu-emdm/nexusUI#72]
Can I do something like this?
var index = select1.choices.indexOf(select1({value: data.text}));

**Comment by adowty** [comment]
slightly remedial javascript, please forgive.
dumped the select object to the console, I see that i should be able to access the object's choice index using data.value.

select1.on('*', function(data) {
	var selText = data.text;
	var selNum = data.value;
	console.log (selText);
	console.log (selNum);
})

text outputs correctly, but value is always 3.

**Comment by adowty** [comment]
...update, I had a line that sets the initial value to 3, when I delete that line, it's undefined.
...so is there no way to access the select value?

**Comment by adowty** [comment]
...to clarify. I need the select object to transmit it's index as an integer.

**Comment by taylorbf** [comment]
Hey there @adowty,

This is a good idea. I will implement it in the update that is currently underway.

If you want a fill for now, you can get the index by rewriting one of the select object's methods. This should do it --

```
select1.change = function( el ) {
	this.val.text = el.value;
	this.val.index = el.selectedIndex;
	this.transmit(this.val);
}
```

This code would apply only to a single select widget -- here called `select1`. Be sure to change that to the name of the variable that you've created for your select object, or use `nx.widgets.select1.change .= ..` if you prefer. Be sure to make this change *after* the select object is created.

Let me know if you have any further questions about getting this to work,

Ben

**Comment by taylorbf** [comment]
Actually, a simpler implementation for you for now would be to simply use `select1.sel.selectedIndex` within your existing callback.

So:

```
select1.on('*',function() {
    console.log( select1.sel.selectedIndex )
})
```

I believe this should work just as well...

**Comment by taylorbf** [comment]
Updated this in #76 . `data.value` will now contain the selection index during output. Thanks for catching this!
