### ISSUE TITLE
How to display warning if nexus doesn't load properly

### ISSUE THREAD

**Issue by gregston** [lsu-emdm/nexusUI#75]
Hi, I'm just using the keyboard on my new site. Nexus doesn't appear to work in IE 9 which is fine, but what's the best way to warn the user that they might not be able to use the page, and need to update the browser? As it is there is no message, the page just doesn't load the keyboard.
Thanks

**Comment by taylorbf** [comment]
Hi gregston,

To answer your question -- when an interface is successfully created, it is added as a property of `nx.widgets`. So if you have created a keyboard:

```
<canvas nx="keyboard" id="keyboard1"></canvas>
```

Then it will be accessible as `nx.widgets.keyboard1`. If it is not created, `nx.widgets.keyboard1` will be undefined. So I think something like this should work:

```
if ( !nx.widgets.keyboard1 ) { 
   // warning code goes in here
}
```

That said, I'd like this to be compatible with IE9... I don't have a way to test, but if another user can track down the bug, I'll do my best to patch. You also might be interested in the [Qwerty-Hancock](https://stuartmemo.com/qwerty-hancock/) project which may be more compatible.

**Comment by gregston** [comment]
Hi Ben,
Thanks for the quick response. I get the problem with IE9 on Vista, but also IE 11 in Windows 10 (OK in Chrome and Safari). The debugger gets as far as:
SCRIPT445: Object doesn't support this action 
referring to the

window.nx = new manager();

line. Meanwhile I'll check out the Hancock thing.

Thanks

Greg Chapman

PS Here's the page:

http://studio-soft.co.uk/chords/

Hope to add it to your portfolio once working!



  ----- Original Message -----

**Comment by gregston** [comment]
Hi
Tried it again and now it seems to trip up with:
this.context = new(window.AudioContext || window.webkitAudioContext)()

with the same 445 message.

  ----- Original Message -----

**Comment by gregston** [comment]
I've got it working in IE9 now. It didn't like:
    document.head.innerHTML = document.head.innerHTML + htmlstr;
as document.head is HTML5 apparently. I've simply added the styles to my style sheet instead.
Also it didn't like
    this.context = new(window.AudioContext || window.webkitAudioContext)()

I don't know enough about js to understand why not, but for my requirements I was able to just comment out this line.
G



  ----- Original Message -----

**Comment by taylorbf** [comment]
Thanks so much for looking into this! I'll push those changes. That is the kind of ugly code I am keeping out of the update I'm working on : )

Your project looks great, by the way! Thanks for sharing. I'll absolutely add this to the library of projects during this update.

Ben

**Comment by gregston** [comment]
Thanks Ben, Great project by the way. I'll add a link if that's OK.
Greg
  ----- Original Message -----

**Comment by taylorbf** [comment]
Fixed the audiocontext code that you pointed out in merge #76 . I'll close this but you can reopen if you still experience an issue.

**Comment by gregston** [comment]
Hi Ben
We were in touch last year about some problems I was having with a Nexus keyboard. That's all sorted, and incidently the page is now at:
http://www.chordnamer.uk/
I'm now trying to make an Android app based on the same page. I want the keyboard to be able to be swiped left and right to show different ranges, so I've put the whole thing inside a 'smoothtouchscroll 'div (http://smoothtouchscroll.com/). I'm developing using Apache Cordova in Visual Studio 2017. Now when I test from VS Studio in a browser (Chrome) window it actually works fine, but when I send it to my actual device, it's not getting the scroll info and 'plays' the wrong note, as if it hadn't moved.
I realise it's difficult for you to know what's going on here, but if you can think of any reason why it should work within the computer but not on the phone...  If not, is there a way to tell the keyboard object that it needs an offset when calculating the key pressed (an offset I'll have to try and get from the scroller). Also, I don't think I'm using Version 2. For what I need do you recommend I update?
Thanks for your time, and some great code!
Greg Chapman



  ----- Original Message -----
