### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by turbo5** [lsu-emdm/nexusUI#77]
The widgets are old, opposed to the main webpage where the new ones are shown.
Also the available config parameters are missing from the documentation, such as min, max, (etc?).

**Comment by taylorbf** [comment]
I just posted the latest API file to the web. Good catch -- I didn't realize it wasn't updating automatically.

There are some parts still missing from the API, such as min/max/step options for dial and slider. For now you can see those options listed under the reference for the Number widget. I can't really do a full API revision, as I'm focusing hard on getting version 2 up a.s.a.p. (see issue #73).

**Comment by taylorbf** [comment]
The widgets aren't showing up in the API now, but the code examples should be up to date. Will get working demos in the API of the update.
