### ISSUE TITLE
Feature request: Matrix - Allow highlighted steps to selected programmatically.

### ISSUE THREAD

**Issue by triss** [lsu-emdm/nexusUI#8]
e.g.
```
matrix.highlightStep(x, y);
matrix.highlightCol(x);
matrix.highlightRow(y);
```

**Comment by taylorbf** [comment]
Hello again Triss,

In the latest build (1.0.5) I have added a .jumpToCol() method which lets you programmatically choose to highlight and output the data from a column of your choice. This will also 'jump' the sequencer to that column if the sequencer is on.

Right now the sequencer is only oriented to move from left to right. But, I am intrigued by your other ideas. I think a y-plane (top to bottom) sequencer which outputs row data would be awesome. That's a feature that I probably won't be able to get around to for a while, but if you would like to implement any awesome matrix features, I would happily accept a pull request!

B
